# Generated by Django 2.1.7 on 2019-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='game_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='taken_to_home',
            field=models.BooleanField(default=True),
        ),
    ]
